api/urls.py
from django.urls import path,include
from api import views
from rest_framework.routers import DefaultRouter

router=DefaultRouter()
router.register(r'users',views.UserViewSet, basename='User')
router.register(r'projects',views.ProjectViewSet, basename='Project')
router.register(r'partners',views.PartnerViewSet,basename='Partner')
router.register(r'project-files',views.ProjectFileViewSet,basename='Project File')

urlpatterns = [
   path('user/',views.UserViewSet.as_view(actions={
        'get':'list',
   }),name='user-list'),
    path('user/<int:pk>/',views.UserViewSet.as_view(actions={
        'get':'retrieve',
    }),name='user-detail'),
    path('project/',views.ProjectViewSet.as_view(actions={
        'get':'list',
        'post':'create',
    }),name='project-list'),
    path('project/<int:pk>/',views.ProjectViewSet.as_view(actions={
        'get':'retrieve',
    }),name='project-detail'),
    path('partner/',views.PartnerViewSet.as_view(actions={
        'get':'list',
        'post':'create',
    }),name='partner-list'),
    path('partner/<int:pk>/',views.PartnerViewSet.as_view(actions={
        'get':'retrieve',
        'patch':'update',
    }),name='partner-detail'),
    path('project-file/', views.ProjectFileViewSet.as_view(actions={
        'get':'list',
        'post':'create'
    }), name='projectfile-detail'),
]

boltnnut/urls.py
from django.urls import path

from . import views

app_name='boltnnut'

urlpatterns = [
    path('', views.index),
    path('projects',views.projects,name='projects'),
    path('uploadProject',views.upload,name='uploadProject'),
    path('search',views.search,name='search'),
    path('services',views.services,name='services'),
]

clonesite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from common.models import User
from rest_framework import routers, serializers, viewsets

# Wire up our API using automatic URL routing
# Additionally, we include login URLs for the browable API.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('boltnnut/', include('boltnnut.urls')),
    path('common/', include('common.urls')),
    path('api/', include('api.urls')),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('signin/', views.signin, name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.signup, name='signup'),
]

boltnnut/models.py
from pydoc import describe
from tkinter import CASCADE
from django.db import models

from common.models import User

# Create your models here.


class Project(models.Model):
    id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200, null=True)
    budget = models.IntegerField(default=0)
    budget_show = models.BooleanField(default=True)
    expired_date = models.DateField(null=True)
    expired_negotiate = models.BooleanField(default=False)
    goal = models.IntegerField(default=1)
    goal_negotiate = models.BooleanField(default=False)
    descript = models.TextField(null=True)
    ongoing = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class ProjectFile(models.Model):
    id = models.AutoField(primary_key=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.FileField(upload_to='Uploaded Files/')

    def __str__(self):
        return self.file


class Partner(models.Model):
    id = models.AutoField(primary_key=True)
    profile = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.CharField(max_length=100, default="익명")
    describe = models.TextField(null=True)
    address = models.CharField(max_length=400, default="정보 없음")
    site = models.CharField(max_length=400, default="정보 없음")
    category = models.CharField(max_length=20, default="전자/반도체 부품")
    thumbnail = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.company

boltnnut/forms.py
'''
 title,
    budget,
    budget_show,
    expired_date,
    expired_negotiation,
    goal,
    goal_negotiation,
    descript,
    attached,
'''
from datetime import date
from django import forms
from .models import Project

class UploadProjectForm(forms.ModelForm):
    title=forms.CharField(
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'name':'title',
                'placeholder':'진행하는 프로젝트 제목을 입력해주세요. ex)반려동물 샤워기'
            }
        ),
        initial='title'
    )
    budget=forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'name':'budget',
            }
        ),
        initial=0
    )
    budget_show=forms.BooleanField(
        initial=True,
        widget=forms.CheckboxInput(
            attrs={
                'name':'budget_show',
                }
        )
    )
    expired_date=forms.DateField(
        widget=forms.DateInput(
            attrs={
                'name':"expired_date",
                'placeholder':"날짜를 선택해주세요."
            }
        ),
        initial=date.today()
    )
    expired_negotiate=forms.BooleanField(
        initial=False,
        widget=forms.CheckboxInput(attrs={
            'name':'expired_negotiate',
        })
    )
    goal=forms.IntegerField(
        widget=forms.DateInput(
            attrs={
                'name':"goal",
                'placeholder':"숫자로 입력하세요."
            }
        ),
        initial=1
    )
    goal_negotiate=forms.BooleanField(
        initial=False,
        widget=forms.CheckboxInput(attrs={
            'name':'goal_negotiate',
            })
    )
    descript=forms.Textarea()

    class Meta:
        model=Project
        fields=['title','budget','budget_show','expired_date','expired_negotiate','goal','goal_negotiate','descript',]

boltnnut/views.py
from unicodedata import category
from django.contrib.auth import login,authenticate
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from .models import Project,Partner,ProjectFile
from common.models import User
from .forms import UploadProjectForm
from django.template import RequestContext

def index(request):
    category=['전자/반도체 부품','생활/위생','디지털/가전','반려','인테리어','주방','볼트/너트류','동력전달부품','냉난방/공조','밴딩/포장']
    context={
        'items':category
    }
    data={}
    for i in category:
        try:
            data[i]=Partner.objects.get(category=i)[3]
        except Partner.DoesNotExist:
            data[i]='null'

    context['data']=data
    return render(request, 'mainsite/index.html', context)


def projects(request):
    context = {

    }
    return render(request, 'mainsite/projects.html', context)


def upload(request):
    if request.method=="POST":
        form=UploadProjectForm(request.POST)
        
        if form.is_valid():
            print("valid")
            user=uploadSignup(request)
            form.save()
            key=Project.objects.last()
            uploadFiles(request,key)
            print(request.FILES)
        else:
            print(form)
    else:
        form=UploadProjectForm()
        return render(request, 'mainsite/uploadProject.html',{'form':form})
    return redirect('/boltnnut/uploadProject')


def uploadFiles(request,key):
    files=request.FILES.getlist('attached')
    print(key)
    print(files)
    for f in files:
        tmp=ProjectFile(file=f,project=key).save()
    return redirect('/boltnnut/')

def uploadSignup(request):
    signup_form=request.POST
    user=User()
    user.email=signup_form['email']
    user.company=signup_form['company']
    user.userType='client'
    password=signup_form['password1']
    password2=signup_form['password2']
    if password==password2:
        user.password=password
    else:
        return
    user.name=signup_form['name']
    user.phone=signup_form['phone']
    user.jobPosition=signup_form['jobPosition']
    user.save()
    return user

def search(request):
    context = {

    }
    return render(request, 'mainsite/search.html', context)


def services(request):
    context = {

    }
    return render(request, 'mainsite/services.html', context)

boltnnut/templates/mainsite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>boltnnut</title>
		<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'styles.css' %}"
		/>		
	</head>
	<body>
		{% include "mainsite/navigation.html" %} 
		{% block content %} 
		{% endblock %}
		{% include "mainsite/foot.html" %}
	</body>
	<script src="{% static 'app.js' %}"></script>
</html>

boltnnut/templates/mainsite/foot.html
{% load static %}
<footer>
	<div class="footer-container">
		<div class="footer__tel">
			<img src="{% static 'images/rowline.svg' %}" alt="" />
			<p>TEL. 02-926-6637</p>
		</div>
		<div class="footer__business-hours">
			<span> 근무 시간 09:00 ~ 18:00 </span>
            <span> 점심 시간 12:00 ~ 13:00 </span>
			<div>토·일요일, 공휴일 휴무</div>
		</div>
		<div>
			<hr />
            <div class="footer__menu">
                <ul>
                    <li class="footer__menu--list">자주찾는 질문</li>
                    <li>|</li>
                    <li class="footer__menu--list">개인정보처리방침</li>
                    <li>|</li>
                    <li class="footer__menu--list">이용약관</li>
                </ul>
            </div>
			<div class="footer__company-info">
                <div>
                    <div>
                        <span> 회사명 </span>
                        <span class="footer__company-info--content">(주) 볼트앤너트</span>
                    </div>
                    <div>
                        <span> 대표자 </span>
                        <spa
                        n class="footer__company-info--content">윤기열</span>
                    </div>
                    <div>
                        <span>사업자등록번호</span>
                        <span class="footer__company-info--content">390-87-01669</span>
                    </div>
                </div>
                <div>
                    <div>
                        <span>사업장 소재지</span>
                        <span class="footer__company-info--content">서울특별시 마포구 마포대로 122 13층 볼트앤너트(공덕동)</span>
                    </div>
                    <div>
                        <span>이메일 </span>
                        <span class="footer__company-info--content">boltnnut@boltnnut.com</span>
                    </div>
                </div>
			</div>
			<hr />
		</div>
	</div>
</footer>

boltnnut/templates/mainsite/index.html
{% extends 'mainsite/base.html' %} 
{% load static %} 
{% block content %}
<div class="banner-container">
    <div class="banner">
        <div class="banner__text">
            <p class="banner__text--big">대한민국 제조사 정보<br>여기 다 있다.</p>
            <p class="banner__text--small">당신에게 맞는 제조사를 바로 찾아보세요.</p>
        </div>
        <div class="banner__search-bar">
            <input type="text" placeholder="금형, 사출성형, 황동, CNC, 플라스틱 ...">
            <img src="{% static 'images/search_blue.svg' %}" alt="검색"/>
        </div>
    </div>
    <div class="company">
        <div class="company__text">
            <p><b>5660개</b>의<br>대한민국 제조사를<br>만나보세요.</p>
        </div>
        <div class="company__list">
            <!--{% for category in items %}
            <div class="company__list__category">{{category}}</div>
            {% for partner in data.category %} 
            <div class="company__list__card">
                <div class="company__list__card__text">
                    <img src="{{partner.thumbnail}}" alt="item.name"/>
                    <h3>{{partner.name}}</h3>
                    <span>{{partner.description}}</span>
                    <img src="{% static 'images/location.svg' %}" alt="주소"/>
                </div>
                <div class="company__list__card__button">
                    <a href="{{partner.site}}"><button class="company__list__card__button--home">홈페이지 방문</button></a>
                    <a href="{% url 'boltnnut:projects' %}"><button class="company__list__card__button--projects">바로 문의하기</button></a>
                </div>
            </div>
            {% endfor %}
            {% endfor %}--> 
        </div>
    </div>
    <div class="find-project">
        <p>더 다양한 분야의 제조사를 찾고 계신가요?</p>
        <a href="{% url 'boltnnut:uploadProject' %}">
            <button>프로젝트 의뢰</button>
        </a>
    </div>
    <div class="banner-steps">
        <div class="banner-steps__image">
            <img src="{% static 'images/step1.png' %}" alt=""/>
        </div>
        <div class="banner-steps__cards">
            <div class="banner-steps__cards__card">
                <div class="banner-steps__cards__card--number">Step1</div>
                <div class="banner-steps__cards__card--text">
                    <h3>제조사 검색</h3>
                    <p>한번의 검색으로 제품에 맞는<br>카테고리의 제조사를 찾아보세요.</p>
                </div>
            </div>
            <div class="banner-steps__cards__card">
                <div class="banner-steps__cards__card--number">Step2</div>
                <div class="banner-steps__cards__card--text">
                    <h3>제조사에 의뢰하기</h3>
                    <p>제조사를 비교하고 간단한 양식에<br>맞춰 견적 요청서를 작성해 보세요.</p>
                </div>
            </div>
            <div class="banner-steps__cards__card">
                <div class="banner-steps__cards__card--number">Step3</div>
                <div class="banner-steps__cards__card--text">
                    <h3>제조사와 직접 채팅하기</h3>
                    <p>제조사에게 견적 요청서를 자세히<br>상담받고 견적을 조율해 보세요.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="banner-reviews">
        <div class="banner-reviews__text">
            <p><b>클라이언트에게 검증</b>된<br>볼트앤너트를 만나보세요.</p>
        </div>
        <div class="banner-reviews__cards">
            <div class="banner-reviews__cards__main-card">
                <div>
                    <div>HCLab</div>
                    <img src="{% static 'images/stars.png' %}" alt="별점"/>
                    <p>개발 업체 찾는 기간이<br>3달이 단축됐습니다.</p>
                    <p>처음에는 100개 정도만 양산을 할 생각으로 여러 업체를 찾아다녔는데 괜찮은 업체를 찾기가 정말 힘들었습니다.<b>업체들과 미팅을 할 때 제조 관련 용어를 몰라 힘이 들었는데,</b> 볼트앤너트를 통해 실질적으로 도움이 되는 다양한 제조 지식을 얻을 수 있었습니다. 무엇보다도 볼트앤너트를 통해 좋은 업체들을 만난 것이 가장 큰 도움이 되었습니다.</p>
                    <div>2020.06.25</div>
                </div>
            </div>
            <div class="banner-reviews__cards__card">
                <div class="banner-reviews__cards__card--default">
                    <div>
                        <div>끌린디</div>
                        <img src="{% static 'images/stars.png' %}" alt="별점"/>
                        <p>처음에는 100개 정도만 양산을 할 생각으로 여러 업체를 찾아다녔는데 괜찮은 업체를 찾기가 정말 힘들었습니다.<b>업체들과 미팅을 할 때 제조 관련 용어를 몰라 힘이 들었는데,</b> 볼트앤너트를 통해 실질적으로 도움이 되는 다양한 제조 지식을 얻을 수 있었습니다. 무엇보다도 볼트앤너트를 통해 좋은 업체들을 만난 것이 가장 큰 도움이 되었습니다.</p>
                        <div>2020.06.25</div>
                    </div>
                </div>
                <div class="banner-reviews__cards__card--default">
                    <div>
                        <div>끌린디</div>
                        <img src="{% static 'images/stars.png' %}" alt="별점"/>
                        <p>처음에는 100개 정도만 양산을 할 생각으로 여러 업체를 찾아다녔는데 괜찮은 업체를 찾기가 정말 힘들었습니다.<b>업체들과 미팅을 할 때 제조 관련 용어를 몰라 힘이 들었는데,</b> 볼트앤너트를 통해 실질적으로 도움이 되는 다양한 제조 지식을 얻을 수 있었습니다. 무엇보다도 볼트앤너트를 통해 좋은 업체들을 만난 것이 가장 큰 도움이 되었습니다.</p>
                        <div>2020.06.25</div>
                    </div>
                </div>
                <div class="banner-reviews__cards__card--default">
                    <div>
                        <div>끌린디</div>
                        <img src="{% static 'images/stars.png' %}" alt="별점"/>
                        <p>처음에는 100개 정도만 양산을 할 생각으로 여러 업체를 찾아다녔는데 괜찮은 업체를 찾기가 정말 힘들었습니다.<b>업체들과 미팅을 할 때 제조 관련 용어를 몰라 힘이 들었는데,</b> 볼트앤너트를 통해 실질적으로 도움이 되는 다양한 제조 지식을 얻을 수 있었습니다. 무엇보다도 볼트앤너트를 통해 좋은 업체들을 만난 것이 가장 큰 도움이 되었습니다.</p>
                        <div>2020.06.25</div>
                    </div>
                </div>
                <div class="banner-reviews__cards__card--default">
                    <div>
                        <div>끌린디</div>
                        <img src="{% static 'images/stars.png' %}" alt="별점"/>
                        <p>처음에는 100개 정도만 양산을 할 생각으로 여러 업체를 찾아다녔는데 괜찮은 업체를 찾기가 정말 힘들었습니다.<b>업체들과 미팅을 할 때 제조 관련 용어를 몰라 힘이 들었는데,</b> 볼트앤너트를 통해 실질적으로 도움이 되는 다양한 제조 지식을 얻을 수 있었습니다. 무엇보다도 볼트앤너트를 통해 좋은 업체들을 만난 것이 가장 큰 도움이 되었습니다.</p>
                        <div>2020.06.25</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

boltnnut/templates/mainsite/navigation.html
{% load static %}
<nav class="navigation">
	<div class="navigation-container" style="justify-self: center">
		<div class="navigation__menu-logo">
			<a class="navigation__brand" href="/boltnnut">
				<img
                    class="navigation__brand--logo"
					src="{% static 'images/bnlogo.svg' %}"
					alt="boltnnut"
				/>
			</a>
			<div class="navigation__menu" id="navbarNav">
				<ul class="navigation__lists">
					<div class="navigation__lists__list">
						<li>
							<a
								class="nav-link"
								href="{% url 'boltnnut:projects' %}"
								>제조사 모집</a
							>
						</li>
						<li>
							<a class="nav-link" href="{% url 'boltnnut:search' %}" >제조사 검색</a>
						</li>
						<li>
							<a
								class="nav-link"
								href="{% url 'boltnnut:services' %}"
								>슈퍼서비스</a
							>
						</li>
					</div>
					<div class="navigation__buttons">
						{% if user.is_authenticated %}
						<li class="navigation__profile">
							<a class="nav-link" href="{% url 'common:logout' %}"
								><span>{{user.name}}&nbsp&nbsp{{user.userType}}</span></a
							>
							<img
								src="{% static 'images/profile.svg' %}"
								alt=""
							/>
						</li>
						<li class="navigation__buttons--log">
							<a class="nav-link" href="{% url 'common:logout' %}"
								>로그아웃</a
							>
						</li>
						{% else %}
						<li
							class="navigation__buttons--signup"
							style="
								background: #eaf0fa;
								color: black;
								display: inline-block;
							"
						>
							<a class="nav-link-signup" href="{% url 'common:signup' %}?next={{request.path}}"
								>회원가입/파트너등록</a
							>
						</li>
						<li class="navigation__buttons--log">
							<a class="nav-link" href="{% url 'common:login' %}?next={{request.path}}"
								>로그인</a
							>
						</li>
						{% endif %}
					</div>
				</ul>
			</div>
		</div>
	</div>
</nav>

boltnnut/templates/mainsite/projects.html
{% extends 'mainsite/base.html' %} {% load static %} {% block content %}
<div class="project-container">
    <div class="project__keyword--title">
        <h2>프로젝트 목록</h2>
    </div>
    <div class="project__lists">
        <div class="project__subhead">
            <div class="project__lists__current">
                <p><b>{{projects|length}}</b>개의 프로젝트가 등록되어있습니다.</p>
            </div>
            <div class="project__lists__submit">
                <p>등록하고 싶은 의뢰가 있으신가요?</p>
                <a href="{% url 'boltnnut:uploadProject' %}">
                    프로젝트 등록하기
                </a>
            </div>
        </div>
        {% for project in projects %}
        <div class="project__lists__card">
            <div class="project__lists__card--status">모집중</div>
            <p>{{project.title}}</p>
            <div class="project__lists__card--info">
                <div>
                    <span>희망 예산</span>
                    <span>{{project.budget}}<span>
                </div>
                <div>
                    <span>희망 수량</span>
                    <span>{{project.goal}}<span>
                </div>
                <div>
                    <span>희망 마감일</span>
                    <span>{{project.expired}}<span>
                </div>
            </div>
        </div> 
        {% endfor %} 
    </div>
</div>
{% endblock %}

boltnnut/templates/mainsite/search.html
{% extends 'mainsite/base.html' %} {% load static %} {% block content %}
<div class="project-container">
    
</div>
{% endblock %}

boltnnut/templates/mainsite/services.html
{% extends 'mainsite/base.html' %} {% load static %} {% block content %}
<div class="project-container">

</div>
{% endblock %}

boltnnut/templates/mainsite/uploadProject.html
{% extends 'mainsite/base.html' %} 
{% load static %} 
{% block content %}
<div class="upload-container">
    <div class="upload__step">
        <ul>
            <li id="uploadStep1" class="upload__step--selected">
                <div>1</div>
                <span>프로젝트 기본 내용을 입력해주세요.</span>
            </li>
            <li id="uploadStep2" class="upload__step--nominee">
                <div>2</div>
                <span>프로젝트 상세 내용을 입력해주세요.(선택)</span>
            </li>
            <li id="uploadStep3" class="upload__step--nominee">
                <div>3</div>
                <span>관련 자료를 업로드해주세요.(선택)</span>
            </li>
            {% if user.is_authenticated %}
            <li id="uploadStepDone" class="upload__step--nominee">
                <div>4</div>
                <span>프로젝트 등록 완료!</span>
            </li>
            {% else %}
            <li id="uploadStep4" class="upload__step--nominee">
                <div>4</div>
                <span>회원가입을 완료해주세요.</span>
            </li>
            <li id="uploadStepDone" class="upload__step--nominee">
                <div>5</div>
                <span>프로젝트 등록 완료</span>
            </li>
            {% endif %}
        </ul>
    </div>
    <form name='uploadProject' method="post" action="{% url 'boltnnut:uploadProject' %}">
        {% csrf_token %}
        <div class="upload__content" value="{{user.is_authenticated}}" status="{{status}}">
            <div class="upload__content--01">
                <section>
                    <h2>프로젝트 기본 내용을 입력해주세요.</h2>
                    <hr>
                </section>
                <section>
                    <h3>프로젝트 제목</h3>
                    {{form.title}}
                </section>
                <section>
                    <h3>희망 예산</h3>
                    <p>예산은 파트너와 협의가 가능합니다. 대략적인 범위를 작성해주세요.</p>
                    {{form.budget}}
                    <div>
                        {{form.budget_show}}
                        <span>파트너에게 예산을 공개하지 않겠습니다.</span>
                    </div>
                </section>
                <section>
                    <h3>프로젝트 희망 마감일</h3>
                    {{form.expired_date}}
                    <div>
                        {{form.expired_negotiate}}<span>기간 협의가 가능합니다.</span></div>
                </section>
                <section>
                    <h3>희망 수량</h3>
                    <p>1,000개 미만은 입찰에 참여하는 파트너의 수가 적을 수 있습니다.</p>
                    {{form.goal}}
                    <div>
                        
                        {{form.goal_negotiate}}
                        <span>수량 협의가 가능합니다.</span>
                    </div>
                </section>
            </div>
            <div class="upload__content--02" >
                <section>
                    <h2>프로젝트 상세 내용을 입력해주세요.</h2>
                    <span>(선택 입력 사항)</span>
                </section>
                <p>기본 내용 외 파트너에게 요청하고 싶은 내용이 있다면 작성해주세요.</p>
                <p><textarea name="descript" value="{{form.descript.value}}">
    1. 프로젝트 목적
    - 제품을 만들게 된 배경, 사용 목적 등을 알면 더 적합한 제작 정보를 드릴 수 있습니다.

    2. 프로젝트 소개 
    - 어떤 제품인지 구체적으로 알려주세요.(주요 기능, 재질, 특징, 사이즈 등)

    3. 참고자료 / 레퍼런스 
    - 참고할만한 제품의 링크나 내용을 적어주시면 더 빠르게 도와드릴 수 있습니다.

    4. 제조사 요청사항
    - 프로젝트에서 가장 중요하게 고려해야하는 것을 알려주세요.
                </textarea></p>
            </div> 
            <div class="upload__content--03">
                <h2>관련 자료를 업로드해주세요.</h2>
                <span>(선택 입력 사항)</span>
                <p>기획 관련 문서, 이미지, 모델링 데이터, 도면 등이 있다면 업로드 해주세요. 
                    <br>파일 용량은 <b>100MB</b>를 넘을 수 없습니다.</p>
                <hr>
                <section class="upload-file" id="uploadFile">
                    <input name="attached" class="upload-file__box" type="file" multiple>
                </section>
            </div>
            {% if user.is_authenticated == False %}        
            <div class="upload__content--04" >
                <h2>회원가입을 완료해주세요.</h2>
                <hr>
                <div class="signup-client__email" id="">
                    <label for="email">이메일</label>
                    <input
                        type="text"
                        class="form-control"
                        name="email"
                        id="email"
                    />
                </div>
                <div class="signup-client__password1">
                    <label for="password1">비밀번호</label>
                    <input 
                        type="password"
                        class="form-control"
                        name="password1"
                        id="password1"
                    />
                </div>
                <div class="signup-client__password2">
                    <label for="password2">비밀번호 확인</label>
                    <input
                        type="password"
                        class="form-control"
                        name="password2"
                        id="password2"
                    />
                </div>
                <div class="signup-client__name">
                    <label for="name">이름</label>
                    <input
                        type="text"
                        class="form-control"
                        name="name"
                        id="name"
                    />
                </div>
                <div class="signup-client__phone">
                    <label for="phone">휴대전화</label>
                    <input
                        type="text"
                        class="form-control"
                        name="phone"
                        id="phone"
                        pattern="^([0-9]{9,11})$"
                    />
                </div>
                <div class="signup-client__company">
                    <label for="company">회사명</label>
                    <input
                        type="text"
                        class="form-control"
                        name="company"
                        id="company"
                    />
                </div>
                <div class="signup-client__jobposition">
                    <label for="jobPosition">직급</label>
                    <input
                        type="text"
                        class="form-control"
                        name="jobPosition"
                        id="jobPosition"
                    />
                </div>
                <div class="signup-client__userType">
                    <input type="text" name="userType" id="userType"/>
                </div>
            </div>
            {% endif %}
            
        </div>
        <section class="upload__content__step-controls">
                <div class="upload__step__previous" id="previous">
                    <span>< 이전</span>
                </div> 
                <div class="upload__step__next" id="next">
                    <span>다음</span>
                </div>  
                <div id="projectSubmit">
                    <button class="upload__step__next" type="submit">등록</a>
                </div>
        </section>
    </form>
</div>
{% endblock %}